no-border
save-position-on-quit
screen=1
volume=20

osd-font     =Victor mono
osd-font-size=35
osd-duration =5000
osd-on-seek  =msg

sub-scale-by-window  =no
sub-scale-with-window=no
sub-pos              =60
sub-font-size        =45
sub-outline-size     =1
sub-spacing          =3
#sub-ass-vsfilter-aspect-compat=no
#sub-ass-vsfilter-blur-compat=no

vo=gpu
hwdec
# dscale=bilinear
priority=high
af=dynaudnorm

force-seekable=yes

keep-open=yes

[movies_tv]
profile-cond=require 'mp.utils'.join_path(working_directory, path):match('[Cc]:\\media[\\$]') ~= nil
saturation=30
volume=80
loop-file=no

[movies]
profile-cond=require 'mp.utils'.join_path(working_directory, path):match('\\movies?[\\$]') ~= nil
sub-file-paths=subs
sub-auto=all

[asoue]
profile-cond=require 'mp.utils'.join_path(working_directory, path):match('\\asoue\\') ~= nil
saturation=100

[w]
profile-cond=require 'mp.utils'.join_path(working_directory, path):match('[XxWx]:') ~= nil
loop-file=inf
saturation=0
volume=20

[pause_on_focus_lost]
profile-cond=not focused
profile-restore=copy-equal
pause=yes

[paused-state]
profile-cond=pause
title="[Paused] ${media-title} - mpv"
profile-restore=copy-equal

[edge-playback]
loop-file=no